// TELEDRIVE — Admin Panel
const COLORS=['#0a84ff','#30d158','#ff9f0a','#bf5af2','#ff453a','#ff375f','#64d2ff','#ffd60a'];

function openAdmin(){
  const{ov,box,close}=modal(`<div class="modal-hd"><div class="modal-ttl"><i class="fas fa-crown" style="color:var(--warning);margin-right:.4rem"></i>Admin Panel</div><button class="modal-x modal-cls"><i class="fas fa-times"></i></button></div><div class="admin-tabs"><div class="admin-tab active" data-t="drives">Drives</div><div class="admin-tab" data-t="settings">Settings</div><div class="admin-tab" data-t="backup">Backup</div></div><div class="admin-tab-bd" id="atbd">${adminDrivesHtml()}</div><div class="modal-ft"><button class="btn-sm d" id="aLogout"><i class="fas fa-sign-out-alt"></i> Logout</button><div style="flex:1"></div><button class="btn-s modal-cls">Close</button></div>`,'admin-box');
  const bd=box.querySelector('#atbd');
  box.querySelectorAll('.admin-tab').forEach(tab=>{tab.onclick=()=>{box.querySelectorAll('.admin-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');const t=tab.dataset.t;bd.innerHTML=t==='drives'?adminDrivesHtml():t==='settings'?adminSettingsHtml():adminBackupHtml();bindAdminTab(t,bd,close,box);};});
  bindAdminTab('drives',bd,close,box);
  box.querySelector('#aLogout').onclick=()=>{S.ses.isAdmin=false;saveSes();close();syncAdminUI();renderHome();toast('Logged out','info');};
}
function adminDrivesHtml(){let h=`<div style="margin-bottom:.9rem"><button class="btn-sm p" id="addDriveBtn"><i class="fas fa-plus"></i> Add Drive</button></div>`;if(!S.db.drives.length)h+=`<div style="text-align:center;padding:2rem;color:var(--text2)">No drives yet.</div>`;S.db.drives.forEach(d=>{const fc=S.db.files.filter(f=>f.driveId===d.id).length;h+=`<div class="drive-row"><div class="drive-row-badge" style="background:${d.color||'var(--primary)'}">${esc(d.letter)}</div><div class="drive-row-info"><div class="drive-row-name">${esc(d.name)} (${esc(d.letter)}:)</div><div class="drive-row-sub">${d.passwordHash?'🔒 Password set':'🔓 No password'} · ${fc} files</div></div><div class="drive-row-acts"><button class="btn-sm editDrBtn" data-id="${d.id}">Edit</button><button class="btn-sm d delDrBtn" data-id="${d.id}">Delete</button></div></div>`;});return h;}
function adminSettingsHtml(){return `<div class="f-grp"><label class="f-lbl">Bot Token</label><input type="password" id="sBt" class="f-inp" value="${esc(S.cfg.botToken)}" placeholder="123456:ABC..."></div><div class="f-grp"><label class="f-lbl">Chat ID</label><input id="sCid" class="f-inp" value="${esc(S.cfg.chatId)}" placeholder="-100..."></div><div class="f-grp"><label class="f-lbl">New Admin Password <span style="color:var(--text3)">(leave blank to keep)</span></label><input type="password" id="sAp" class="f-inp" placeholder="New password..."></div><div style="margin-top:.5rem"><button class="btn-sm p" id="saveSetBtn">Save Settings</button></div>`;}
function adminBackupHtml(){const fc=S.db.files.length,fld=S.db.folders.length,db=S.db.drives.length,sz=(JSON.stringify(S.db).length/1024).toFixed(1);return `<div class="info-box"><strong>Database:</strong> ${db} drives · ${fld} folders · ${fc} files · ${sz} KB (Upstash)</div><div style="display:flex;flex-direction:column;gap:.9rem"><div><button class="btn-sm p" id="bkExport"><i class="fas fa-download"></i> Export Backup JSON</button><div class="f-hint">Download all metadata. Files stay on Telegram.</div></div><div><button class="btn-sm" id="bkImport"><i class="fas fa-upload"></i> Import Backup</button><input type="file" id="bkFile" accept=".json" hidden><div class="f-hint">Restore from backup.</div></div><div><button class="btn-sm p" id="bkSync"><i class="fas fa-sync"></i> Force Sync to Upstash</button></div><div><button class="btn-sm" id="bkReload"><i class="fas fa-cloud-download-alt"></i> Reload from Upstash</button></div></div>`;}
function bindAdminTab(t,bd,closeAdmin,box){
  if(t==='drives'){
    bd.querySelector('#addDriveBtn')?.addEventListener('click',()=>{closeAdmin();setTimeout(()=>createDriveDialog(()=>openAdmin()),200);});
    bd.querySelectorAll('.editDrBtn').forEach(btn=>btn.addEventListener('click',()=>{const d=S.db.drives.find(x=>x.id===btn.dataset.id);if(d){closeAdmin();setTimeout(()=>editDriveDialog(d,()=>openAdmin()),200);}}));
    bd.querySelectorAll('.delDrBtn').forEach(btn=>btn.addEventListener('click',async()=>{const d=S.db.drives.find(x=>x.id===btn.dataset.id);if(d&&confirm(`Delete drive "${d.name}" and ALL files?`)){await deleteDrive(d);bd.innerHTML=adminDrivesHtml();bindAdminTab('drives',bd,closeAdmin,box);}}));
  }
  if(t==='settings'){bd.querySelector('#saveSetBtn')?.addEventListener('click',async()=>{const bt=bd.querySelector('#sBt').value.trim();const cid=bd.querySelector('#sCid').value.trim();const ap=bd.querySelector('#sAp').value;if(bt)S.cfg.botToken=bt;if(cid)S.cfg.chatId=cid;if(ap)S.db.adminHash=await sha256(ap);saveCfg();const ok=await saveDB();toast(ok?'Settings saved':'Saved locally (Upstash failed)',ok?'success':'warning');});}
  if(t==='backup'){
    bd.querySelector('#bkExport')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(S.db,null,2)],{type:'application/json'});dlLink(URL.createObjectURL(blob),`teledrive_backup_${new Date().toISOString().slice(0,10)}.json`);toast('Backup exported','success');});
    bd.querySelector('#bkImport')?.addEventListener('click',()=>bd.querySelector('#bkFile').click());
    bd.querySelector('#bkFile')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const d=JSON.parse(await file.text());if(!d.v||!d.drives)throw new Error('Invalid');S.db=d;await saveDB();renderHome();bd.innerHTML=adminBackupHtml();bindAdminTab('backup',bd,closeAdmin,box);toast('Backup restored','success');}catch(e){toast('Import failed: '+e.message,'error');}});
    bd.querySelector('#bkSync')?.addEventListener('click',async()=>{const btn=bd.querySelector('#bkSync');btn.disabled=true;btn.textContent='Syncing...';const ok=await saveDB();btn.disabled=false;btn.innerHTML='<i class="fas fa-sync"></i> Force Sync to Upstash';toast(ok?'Synced':'Sync failed',ok?'success':'error');});
    bd.querySelector('#bkReload')?.addEventListener('click',async()=>{const ok=await loadDB();renderHome();toast(ok?'Reloaded':'Reload failed',ok?'success':'error');});
  }
}
function createDriveDialog(cb){let color=COLORS[0];const{box,close}=modal(`<div class="modal-hd"><div class="modal-ttl">Create Drive</div><button class="modal-x modal-cls"><i class="fas fa-times"></i></button></div><div class="modal-bd"><div class="f-grp"><label class="f-lbl">Drive Name</label><input id="cdName" class="f-inp" placeholder="e.g. My Drive" autofocus></div><div class="f-grp"><label class="f-lbl">Drive Letter</label><input id="cdLetter" class="f-inp" placeholder="T" maxlength="1" style="text-transform:uppercase;width:80px"></div><div class="f-grp"><label class="f-lbl">Color</label><div class="color-grid" id="colorGrid">${COLORS.map((c,i)=>`<div class="c-swatch${i===0?' active':''}" data-c="${c}" style="background:${c}"></div>`).join('')}</div></div><div class="f-grp"><label class="f-lbl">Password (optional)</label><input type="password" id="cdPass" class="f-inp" placeholder="Leave blank for no password"></div></div><div class="modal-ft"><button class="btn-s modal-cls">Cancel</button><button id="cdCreate" class="btn-p">Create Drive</button></div>`);box.querySelectorAll('.c-swatch').forEach(s=>{s.onclick=()=>{color=s.dataset.c;box.querySelectorAll('.c-swatch').forEach(x=>x.classList.remove('active'));s.classList.add('active');};});box.querySelector('#cdLetter').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z]/g,'');box.querySelector('#cdCreate').onclick=async()=>{const name=box.querySelector('#cdName').value.trim();const letter=box.querySelector('#cdLetter').value.trim().toUpperCase();const pass=box.querySelector('#cdPass').value;if(!name||!letter){toast('Fill in name and letter','error');return;}if(S.db.drives.find(d=>d.letter===letter)){toast('Letter already in use','error');return;}S.db.drives.push({id:uid(),letter,name,color,passwordHash:pass?await sha256(pass):null,createdAt:new Date().toISOString()});await saveDB();close();renderHome();toast(`Drive ${letter}: created`,'success');if(cb)cb();};}
function editDriveDialog(drive,cb){const{box,close}=modal(`<div class="modal-hd"><div class="modal-ttl">Edit Drive — ${esc(drive.letter)}:</div><button class="modal-x modal-cls"><i class="fas fa-times"></i></button></div><div class="modal-bd"><div class="f-grp"><label class="f-lbl">Drive Name</label><input id="edName" class="f-inp" value="${esc(drive.name)}" autofocus></div><div class="f-grp"><label class="f-lbl">${drive.passwordHash?'Change Password':'Set Password (optional)'}</label><input type="password" id="edPass" class="f-inp" placeholder="${drive.passwordHash?'New password...':'Leave blank for no password'}">${drive.passwordHash?'<div class="f-hint"><label><input type="checkbox" id="edRemPass" style="margin-right:.3rem"> Remove password</label></div>':''}</div></div><div class="modal-ft"><button class="btn-s modal-cls">Cancel</button><button id="edSave" class="btn-p">Save</button></div>`);box.querySelector('#edSave').onclick=async()=>{const name=box.querySelector('#edName').value.trim();const pass=box.querySelector('#edPass').value;const rem=box.querySelector('#edRemPass')?.checked;const d=S.db.drives.find(x=>x.id===drive.id);if(d){if(name)d.name=name;if(rem)d.passwordHash=null;else if(pass)d.passwordHash=await sha256(pass);}await saveDB();close();renderHome();toast('Drive updated','success');if(cb)cb();};}
async function deleteDrive(d){const files=S.db.files.filter(f=>f.driveId===d.id);for(const f of files)for(const c of f.chunks)await tgDelete(c.msgId);S.db.files=S.db.files.filter(f=>f.driveId!==d.id);S.db.folders=S.db.folders.filter(f=>f.driveId!==d.id);S.db.drives=S.db.drives.filter(x=>x.id!==d.id);await saveDB();renderHome();toast(`Drive ${d.letter}: deleted`,'success');}