// TELEDRIVE — Dialogs
// FIX: querySelectorAll so ALL .modal-cls close the modal (Cancel button works!)
function modal(html,cls=''){
  const ov=document.createElement('div');ov.className='modal-ov';
  const box=document.createElement('div');box.className=`modal-box ${cls}`;box.innerHTML=html;
  ov.appendChild(box);document.body.appendChild(ov);
  const close=()=>ov.remove();
  box.querySelectorAll('.modal-cls').forEach(el=>el.addEventListener('click',close));
  ov.addEventListener('click',e=>{if(e.target===ov)close();});
  document.addEventListener('keydown',function h(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',h);}});
  return{ov,box,close};
}
function confirmDeleteFile(f){const{box,close}=modal(`<div class="modal-hd"><div class="modal-ttl">Delete File</div><button class="modal-x modal-cls"><i class="fas fa-times"></i></button></div><div class="modal-bd" style="text-align:center;padding:1.4rem"><div style="width:50px;height:50px;border-radius:50%;background:rgba(255,69,58,.12);color:var(--danger);display:flex;align-items:center;justify-content:center;font-size:1.2rem;margin:0 auto .8rem"><i class="fas fa-trash"></i></div><h3 style="margin-bottom:.4rem;font-size:1rem">Delete "${esc(f.name)}"?</h3><p style="color:var(--text2);font-size:.84rem">This will permanently remove the file from Telegram.</p></div><div class="modal-ft"><button class="btn-s modal-cls">Cancel</button><button id="cfDel" class="btn-d">Delete</button></div>`);box.querySelector('#cfDel').onclick=async()=>{close();await deleteFile(f);};}
function confirmDeleteFolder(f){const{box,close}=modal(`<div class="modal-hd"><div class="modal-ttl">Delete Folder</div><button class="modal-x modal-cls"><i class="fas fa-times"></i></button></div><div class="modal-bd" style="text-align:center;padding:1.4rem"><div style="width:50px;height:50px;border-radius:50%;background:rgba(255,69,58,.12);color:var(--danger);display:flex;align-items:center;justify-content:center;font-size:1.2rem;margin:0 auto .8rem"><i class="fas fa-folder"></i></div><h3 style="margin-bottom:.4rem;font-size:1rem">Delete "${esc(f.name)}"?</h3><p style="color:var(--text2);font-size:.84rem">All files inside will be deleted from Telegram too.</p></div><div class="modal-ft"><button class="btn-s modal-cls">Cancel</button><button id="cfFldel" class="btn-d">Delete All</button></div>`);box.querySelector('#cfFldel').onclick=async()=>{close();await deleteFolder(f);};}
function confirmDeleteDrive(d){const{box,close}=modal(`<div class="modal-hd"><div class="modal-ttl">Delete Drive</div><button class="modal-x modal-cls"><i class="fas fa-times"></i></button></div><div class="modal-bd" style="text-align:center;padding:1.4rem"><div style="width:50px;height:50px;border-radius:50%;background:rgba(255,69,58,.12);color:var(--danger);display:flex;align-items:center;justify-content:center;font-size:1.2rem;margin:0 auto .8rem"><i class="fas fa-hard-drive"></i></div><h3 style="margin-bottom:.4rem;font-size:1rem">Delete "${esc(d.name)} (${esc(d.letter)}:)"?</h3><p style="color:var(--text2);font-size:.84rem">ALL files on this drive will be deleted from Telegram.</p></div><div class="modal-ft"><button class="btn-s modal-cls">Cancel</button><button id="cfDrv" class="btn-d">Delete Drive</button></div>`);box.querySelector('#cfDrv').onclick=async()=>{close();await deleteDrive(d);};}
function newFolderDlg(){const{box,close}=modal(`<div class="modal-hd"><div class="modal-ttl"><i class="fas fa-folder-plus" style="color:var(--warning);margin-right:.4rem"></i>New Folder</div><button class="modal-x modal-cls"><i class="fas fa-times"></i></button></div><div class="modal-bd"><div class="f-grp"><label class="f-lbl">Folder Name</label><input id="nfName" class="f-inp" placeholder="e.g. Documents" autofocus></div></div><div class="modal-ft"><button class="btn-s modal-cls">Cancel</button><button id="nfCreate" class="btn-p">Create</button></div>`);const create=async()=>{const name=box.querySelector('#nfName').value.trim();if(!name){toast('Enter a name','error');return;}S.db.folders.push({id:uid(),driveId:S.driveId,parentId:S.folderId,name,createdAt:new Date().toISOString()});close();await saveDB();renderExplorer();toast(`"${name}" created`,'success');};box.querySelector('#nfCreate').onclick=create;box.querySelector('#nfName').onkeydown=e=>{if(e.key==='Enter')create();};}
function renameFolderDlg(folder){const{box,close}=modal(`<div class="modal-hd"><div class="modal-ttl">Rename Folder</div><button class="modal-x modal-cls"><i class="fas fa-times"></i></button></div><div class="modal-bd"><div class="f-grp"><label class="f-lbl">New Name</label><input id="rfName" class="f-inp" value="${esc(folder.name)}" autofocus></div></div><div class="modal-ft"><button class="btn-s modal-cls">Cancel</button><button id="rfSave" class="btn-p">Rename</button></div>`);box.querySelector('#rfSave').onclick=async()=>{const name=box.querySelector('#rfName').value.trim();if(!name)return;const f=S.db.folders.find(x=>x.id===folder.id);if(f)f.name=name;close();await saveDB();renderExplorer();toast('Folder renamed','success');};}
async function promptPass(drive){const{box,close}=modal(`<div class="modal-hd"><div class="modal-ttl">🔒 Drive Locked</div><button class="modal-x modal-cls"><i class="fas fa-times"></i></button></div><div class="modal-bd" style="text-align:center"><div class="pass-lock"><i class="fas fa-lock"></i></div><h3 style="margin-bottom:.3rem">${esc(drive.name)} (${esc(drive.letter)}:)</h3><p style="color:var(--text2);font-size:.83rem;margin-bottom:1.2rem">Enter password to unlock this drive</p><div class="f-grp" style="text-align:left"><input type="password" id="dpass" class="f-inp" placeholder="Password..." autofocus></div><div id="dpassErr" class="f-err" style="min-height:1rem"></div></div><div class="modal-ft"><button class="btn-s modal-cls">Cancel</button><button id="dpassOk" class="btn-p"><i class="fas fa-unlock"></i> Unlock</button></div>`,'pass-box');const unlock=async()=>{const p=box.querySelector('#dpass').value;const h=await sha256(p);if(h===drive.passwordHash){S.ses.unlocked.push(drive.id);saveSes();close();nav(drive.id);}else{box.querySelector('#dpassErr').textContent='Incorrect password.';box.querySelector('#dpass').value='';}};box.querySelector('#dpassOk').onclick=unlock;box.querySelector('#dpass').onkeydown=e=>{if(e.key==='Enter')unlock();};}
function promptAdminLogin(){const{box,close}=modal(`<div class="modal-hd"><div class="modal-ttl"><i class="fas fa-crown" style="color:var(--warning);margin-right:.4rem"></i>Admin Login</div><button class="modal-x modal-cls"><i class="fas fa-times"></i></button></div><div class="modal-bd"><div class="f-grp"><label class="f-lbl">Admin Password</label><input type="password" id="apass" class="f-inp" placeholder="Enter admin password..." autofocus></div><div id="apassErr" class="f-err"></div></div><div class="modal-ft"><button class="btn-s modal-cls">Cancel</button><button id="apassOk" class="btn-p">Login</button></div>`);const login=async()=>{const p=box.querySelector('#apass').value;const h=await sha256(p);if(h===S.db.adminHash){S.ses.isAdmin=true;saveSes();close();toast('Admin access granted','success');syncAdminUI();renderHome();openAdmin();}else{box.querySelector('#apassErr').textContent='Incorrect password.';box.querySelector('#apass').value='';}};box.querySelector('#apassOk').onclick=login;box.querySelector('#apass').onkeydown=e=>{if(e.key==='Enter')login();};}
function showAdmin(){if(!S.ses.isAdmin){promptAdminLogin();return;}openAdmin();}